# Generated by Django 4.1.7 on 2023-05-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='locations',
            new_name='city',
        ),
    ]
